name       : projectm
version    : 3.1.8
release    : 5
source     :
    - https://github.com/projectM-visualizer/projectm/archive/v3.1.8.tar.gz : cb52e7f4e72b1b60e7a2a5e1a7b110b909c42b622a9fb328b4e7b186614f51a0
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Advanced music visualization program
description: |
    projectM is an open-source project that reimplements the esteemed Winamp Milkdrop by Geiss in a more modern, cross-platform reusable library.

    Its purpose in life is to read in audio input and produce mesmerizing visuals, detecting tempo, and rendering advanced equations into a limitless array of user-contributed visualizations.
builddeps  :
    - pkgconfig(ftgl)
    - pkgconfig(glm)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
setup      : |
    %reconfigure --disable-static \
        --enable-threading \
        --enable-qt \
        --enable-sdl \
        --enable-gles
build      : |
    %make
install    : |
    %make_install
