name       : projectm
version    : 3.1.0
release    : 4
source     :
    - https://github.com/projectM-visualizer/projectm/archive/v3.1.0.tar.gz : 8ddf99dc141e554d76a2ecf8d8c1fe7996051e30fa8dd4fc133ce024c8defba7
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : Advanced music visualization program
description: |
    projectM is an open-source project that reimplements the esteemed Winamp Milkdrop by Geiss in a more modern, cross-platform reusable library.

    Its purpose in life is to read in audio input and produce mesmerizing visuals, detecting tempo, and rendering advanced equations into a limitless array of user-contributed visualizations.
builddeps  :
    - pkgconfig(ftgl)
    - pkgconfig(glm)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
setup      : |
    %reconfigure --disable-static \
        --enable-threading \
        --enable-qt \
        --enable-sdl \
        --enable-gles
build      : |
    %make
install    : |
    %make_install
